name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  convert:
    name: Convert md to html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: create target folder
        run: mkdir my-app/public/data
      - name: Run script
        run: cd converter && cargo run && cd ..
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'latest'
      - name: Change directory
        run: cd my-app
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
