name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    name: Convert md to html and build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: create target folder
        run: mkdir my-app/public/data
      - name: Run script
        run: cargo run
        working-directory: converter
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: my-app
      - name: Build
        run: npm run build
        working-directory: my-app
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './my-app/dist'
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: Deployment
        uses: actions/deploy-pages@v2
